//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bike.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    public partial class BikeData1
    {

        public int BikeId { get; set; }
        [Required(ErrorMessage = "Name Is Required")]
        public string BikeName { get; set; }
        public string Color { get; set; }
        public string MaxPower { get; set; }
        public string EngineType { get; set; }
        public string MaxSpeed { get; set; }
        public string Aversge { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CategoryName { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
